language: 
  - python
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - coverage run --source=cogfusion setup.py test
  - python setup.py sdist
after_success:
  - coveralls
deploy:
    provider: script
    script: deploy.sh
    on:
      branch: master
