#!/usr/bin/python
# -*- coding: UTF-8 -*-
import argparse
import cogfusion.webapp

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest="command",
    title='subcommands')

serve = subparsers.add_parser('serve',
    help='Start a webserver to interact with Cogfusion.')

args = parser.parse_args()
if args.command == 'serve':
    cogfusion.webapp.serve()

